name: App CI

on:
  push:
    branches:
      - main

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versin: [18.x, 20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'


      - name: Install server dependancies
        working-directory: server
        run: npm ci

      - name: Build server
        working-directory: server
        run: npm run build
  frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versin: [18.x, 20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'


      - name: Install frontend dependancies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build
